# INTRO

[[exercises]]
name = "00_compiling"
path = "exercises/00_compiling"
mode = "risc0run"
hint = """
Remove the `I AM NOT DONE` comment in the `exercises/intro00/intro1.rs` file
to move on to the next exercise."""

[[exercises]]
name = "test"
path = "exercises/01_input"
mode = "risc0run"
hint = """
Remove the `I AM NOT DONE` comment in the `exercises/intro00/intro1.rs` file
to move on to the next exercise."""