[package]
name = "host"
version = "0.1.0"
edition = "2021"
build = "../../shared/build.rs"

[dependencies]
risc0-zkvm = { version = "=1.0.0-rc.5" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
anyhow = "1.0"

[build-dependencies]
risc0-build = "=1.0.0-rc.5"
